name: heartlink
description: A beautiful dating app with real connections
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.5
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.7.0
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  http: ^1.1.2
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Image Handling
  image_picker: ^1.0.5
  flutter_image_compress: ^2.1.0
  
  # Swipe Cards
  flutter_card_swiper: ^6.0.0
  
  # WebSocket & Real-time
  web_socket_channel: ^2.4.0
  
  # Utils
  intl: ^0.18.1
  timeago: ^3.6.0
  url_launcher: ^6.2.2
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FF6B9D"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
